name: 'Python Package Shared Action'
description: 'Python Package Shared Action'
inputs:
  python-version:
    description: "Version range or exact version of a Python version to use."
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        pip install poetry
        make install
      shell: bash

    - name: Run tests
      run: make test
      shell: bash

    - name: Check coding standards
      run: make lint
      shell: bash

    - name: Ensure package builds
      run: poetry build
      shell: bash

    - name: Upload coverage report to codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
