name: 'Python Package Shared Action'
description: 'Python Package Shared Action'
inputs:
  python-version:
    description: "Version range or exact version of a Python version to use."
    required: true
  pre-install:
    description: "Packages to pip install before running make install."
  run-lint:
    description: "If 'true', run `make lint`. Otherwise, skip it."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        pip install ${{ inputs.pre-install }}
        make install
      shell: bash

    - name: Run tests
      run: make test
      shell: bash

    - name: Check coding standards
      if: ${{ inputs.run-lint == 'true' }}
      run: make lint
      shell: bash

    - name: Ensure package builds
      run: make build
      shell: bash

    - name: Upload coverage report to codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./coverage.xml
        name: coverage-${{ inputs.python-version }}
